[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "careers_wealth_comparison"
version = "0.0.1"
description = "A repository to compare wealth outcomes depending on career choices"
authors = [
  { name = "Ulises Rey" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "mkdocs",
    "pandas>=2.0",
    "pip",
    "plotly>=5.0",
    "python-dotenv",
    "ruff",
    "streamlit>=1.30",
]
requires-python = "~=3.10.0"

[tool.uv]
dev-dependencies = ["pytest>=7.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.ruff]
line-length = 99
src = ["careers_wealth_comparison"]
include = ["pyproject.toml", "careers_wealth_comparison/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["careers_wealth_comparison"]
force-sort-within-sections = true

